
backend:
  name: github
  repo: yassinred1119/academy-droit # اسم المستودع الخاص بك
  branch: main
media_folder: "assets/images" # المجلد الذي ستُحفظ فيه الصور
public_folder: "/assets/images" # الرابط العام للصور
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
